baseURL = "/"
languageCode = "en-us"
title = "Heytaco Anywhere 🌮"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 10

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Heytaco Anywhere is 3rd party plugin of Heytaco.'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  mainSections = ["docs", "price", "privacy"]

  [params.homepage_meta_tags]
    meta_description = "Heytaco Anywhere is 3rd party plugin of Heytaco."
    meta_og_title = "Heytaco Anywhere"
    meta_og_type = "website"
    meta_og_url = "https://heytaco-anywhere.chat"
    meta_og_image = "https://heytaco-anywhere.chat/images/site.png"
    meta_og_description = "Heytaco Anywhere is 3rd party plugin of Heytaco."
    meta_twitter_card = "summary"
    meta_twitter_site = "@HeytacoA"
    meta_twitter_creator = "@HeytacoA"

  [params.logo]
      mobile = "/images/taco.png"
      standard  = "/images/taco.png"
