baseURL = "/"
languageCode = "en-us"
title = "Heytaco Anywhere 🌮"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'Heytaco Anywhere is 3rd party plugin of Heytaco.'
  homepage_image = '/images/taco.png'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  mainSections = ["docs", "price", "privacy"]

  [params.homepage_meta_tags]
    meta_description = "Heytaco Anywhere is 3rd party plugin of Heytaco."
    meta_og_title = "Heytaco Anywhere"
    meta_og_type = "website"
    meta_og_url = "https://hugo-whisper.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Heytaco Anywhere is 3rd party plugin of Heytaco."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/taco.png"
